application: jirawavebot
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: jirawavebot.py
- url: /assets
  static_dir: assets
- url: /favicon.ico
  static_files: assets/python.jpg
  upload: assets/.*